import {
  DailyReadiness,
  MorningMobilityRoutine,
  NightlyStretchingRoutine,
  ScheduledEvent,
  UserProfile,
  WorkoutPlan,
  ChatMessage,
  PlyometricsRoutine,
  SchoolWorkoutLog
} from '../types';
import { generateLocalWorkoutPlan } from './fitnessEngine';
import { getTodayDateString } from '../utils/dateUtils';
import { supabase } from './supabase';
import { apiFetch } from './api';

const STORAGE_KEYS = {
  USER_ACCOUNT: 'ai_coach_user_account_v1', USER_PROFILE: 'ai_coach_user_profile_v1', TODAY_WORKOUT: 'ai_coach_today_workout_v1', DAILY_READINESS: 'ai_coach_daily_readiness_v1', SCHEDULED_EVENTS: 'ai_coach_scheduled_events_v1', WORKOUT_HISTORY: 'ai_coach_workout_history_v1', EXERCISE_PERFORMANCE: 'ai_coach_exercise_perf_v1', MORNING_MOBILITY: 'ai_coach_morning_mobility_v1', NIGHTLY_ROUTINE: 'ai_coach_nightly_routine_v1', PLYOMETRICS_ROUTINE: 'lifted_plyometrics_routine_v1', SCHOOL_WORKOUT_LOGS: 'lifted_school_workout_logs_v1', CHAT_MESSAGES: 'ai_coach_chat_messages_v1', CUSTOM_TEMPLATES: 'lifted_custom_workout_templates_v1', ADDITIONAL_WORKOUT: 'lifted_additional_workout_v1', ACTIVITY_LOG: 'lifted_activity_completion_v1'
};

export const DEFAULT_PROFILE: UserProfile = { id:'user-default', name:'Athlete', age:18, height:'', weight:'', experienceLevel:'intermediate', goals:['Athletic Performance','Strength','Injury Prevention'], sport:'General Athletics', sportDetails:{position:'',trainingFrequency:'3-4x per week',mainPerformanceGoals:''}, equipmentProfile:'full_gym', availableEquipment:['barbell','dumbbell','cable_machine','bench','pull_up_bar','resistance_bands'], weightUnit:'lb', limitations:[], specificInjuries:[], dislikedExercises:[], favoriteExercises:[], neverRecommendExercises:[], preferredWorkoutDuration:35, onboardingCompleted:false };
export const DEFAULT_READINESS: DailyReadiness = { date:getTodayDateString(), energyLevel:'good', sorenessLevel:'none', practiceEarlierToday:false, practiceLaterToday:false, practiceIntensity:'moderate', practiceDurationMinutes:90, availableMinutes:35, readinessScore:8 };
const DEFAULT_SCHEDULED_EVENTS: ScheduledEvent[] = [];
const parse = <T,>(key:string,fallback:T):T => { try { const raw=localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } };
const save = (key:string,value:unknown) => { try { localStorage.setItem(key,JSON.stringify(value)); } catch {} };

export const StorageService = {
  getUserProfile():UserProfile { const saved=parse<UserProfile|null>(STORAGE_KEYS.USER_PROFILE,null); if(!saved)return DEFAULT_PROFILE; return {...DEFAULT_PROFILE,...saved,goals:Array.isArray(saved.goals)?saved.goals:DEFAULT_PROFILE.goals,availableEquipment:Array.isArray(saved.availableEquipment)?saved.availableEquipment:DEFAULT_PROFILE.availableEquipment,limitations:Array.isArray(saved.limitations)?saved.limitations:[],specificInjuries:Array.isArray(saved.specificInjuries)?saved.specificInjuries:[],dislikedExercises:Array.isArray(saved.dislikedExercises)?saved.dislikedExercises:[],favoriteExercises:Array.isArray(saved.favoriteExercises)?saved.favoriteExercises:[],neverRecommendExercises:Array.isArray(saved.neverRecommendExercises)?saved.neverRecommendExercises:[]}; },
  saveUserProfile(profile:UserProfile){save(STORAGE_KEYS.USER_PROFILE,profile);},
  getDailyReadiness():DailyReadiness{const today=getTodayDateString();const saved=parse<DailyReadiness|null>(STORAGE_KEYS.DAILY_READINESS,null);return saved?.date===today?saved:{...DEFAULT_READINESS,date:today};},
  saveDailyReadiness(r:DailyReadiness){save(STORAGE_KEYS.DAILY_READINESS,r);},
  getScheduledEvents():ScheduledEvent[]{const events=parse<ScheduledEvent[]>(STORAGE_KEYS.SCHEDULED_EVENTS,DEFAULT_SCHEDULED_EVENTS);return Array.isArray(events)?events.filter(e=>e.id!=='evt-practice-today'):[];},
  saveScheduledEvents(e:ScheduledEvent[]){save(STORAGE_KEYS.SCHEDULED_EVENTS,e);}, addScheduledEvent(e:ScheduledEvent){this.saveScheduledEvents([...this.getScheduledEvents(),e]);}, removeScheduledEvent(id:string){this.saveScheduledEvents(this.getScheduledEvents().filter(e=>e.id!==id));},
  getTodayWorkout():WorkoutPlan{const today=getTodayDateString();const saved=parse<any>(STORAGE_KEYS.TODAY_WORKOUT,null);const plan:WorkoutPlan|null=saved?.exercises?saved:saved?.plan||null; if(plan&&Array.isArray(plan.exercises)&&plan.exercises.length&&plan.date===today)return plan; return {id:`ready-${today}`,date:today,workoutTitle:'Ready when you are',goal:'Sport performance, strength & durability',status:'planned',estimatedMinutes:this.getUserProfile().preferredWorkoutDuration,readinessStatus:'Moderate Readiness',reasoning:'Complete the pre-workout check-in and explicitly generate today’s workout.',practiceLaterToday:false,isAiGenerated:true,equipmentNeeded:[],exercises:[],needsGeneration:true} as WorkoutPlan;},
  saveTodayWorkout(workout:WorkoutPlan){save(STORAGE_KEYS.TODAY_WORKOUT,workout?.exercises?workout:(workout as any)?.plan||workout);}, getCurrentWorkoutPlan(){return this.getTodayWorkout();}, saveCurrentWorkoutPlan(w:WorkoutPlan){this.saveTodayWorkout(w);}, resetTodayWorkout(){try{localStorage.removeItem(STORAGE_KEYS.TODAY_WORKOUT);}catch{} return this.getTodayWorkout();},
  getAdditionalWorkout(){const p=parse<WorkoutPlan|null>(STORAGE_KEYS.ADDITIONAL_WORKOUT,null);return p?.date===getTodayDateString()?p:null;}, saveAdditionalWorkout(w:WorkoutPlan){save(STORAGE_KEYS.ADDITIONAL_WORKOUT,w);}, deleteAdditionalWorkout(){try{localStorage.removeItem(STORAGE_KEYS.ADDITIONAL_WORKOUT);}catch{}},
  getWorkoutHistory(){const h=parse<WorkoutPlan[]>(STORAGE_KEYS.WORKOUT_HISTORY,[]);return Array.isArray(h)?h.filter(w=>w.id!=='hist-1'):[];}, saveWorkoutHistory(h:WorkoutPlan[]){save(STORAGE_KEYS.WORKOUT_HISTORY,h);},
  getExercisePerformanceMap(){return parse<Record<string,any>>(STORAGE_KEYS.EXERCISE_PERFORMANCE,{});}, saveExercisePerformanceMap(m:Record<string,any>){save(STORAGE_KEYS.EXERCISE_PERFORMANCE,m);}, rebuildExercisePerformanceMap(history:WorkoutPlan[]=this.getWorkoutHistory()){const map:Record<string,any>={};[...history].sort((a,b)=>a.date.localeCompare(b.date)).forEach(w=>{if(w.status!=='completed'&&!w.completedAt)return;(w.exercises||[]).forEach(ex=>{const sets=(ex.completedSets||[]).filter(s=>s.completed&&Number(s.weight)>=0&&Number(s.reps)>0);if(!sets.length&&!ex.completed)return;const best=sets.length?sets.reduce((a,b)=>Number(b.weight)>Number(a.weight)?b:a):{weight:ex.actualWeightUsed??ex.recommendedWeight,reps:ex.reps};const record={weight:Number(best.weight)||0,reps:Number(best.reps)||0,difficulty:ex.feedbackDifficulty||'just_right',painReported:Boolean(ex.painReported),feedbackNote:ex.feedbackNote||'',date:w.date};map[ex.exerciseId]=record;map[ex.name.toLowerCase().trim()]=record;});});this.saveExercisePerformanceMap(map);}, recordExercisePerformance(w:WorkoutPlan){if(w?.status==='completed'||w?.completedAt)this.rebuildExercisePerformanceMap(this.getWorkoutHistory());},
  addCompletedWorkout(w:WorkoutPlan){const h=this.getWorkoutHistory();h.unshift(w);this.saveWorkoutHistory(h);this.rebuildExercisePerformanceMap(h);}, deleteWorkoutHistoryItem(id:string){const h=this.getWorkoutHistory().filter(w=>w.id!==id);this.saveWorkoutHistory(h);this.rebuildExercisePerformanceMap(h);if(this.getAdditionalWorkout()?.id===id)this.deleteAdditionalWorkout();}, clearAllWorkoutHistory(){this.saveWorkoutHistory([]);this.saveExercisePerformanceMap({});this.resetTodayWorkout();},
  getMorningMobility(){return parse<MorningMobilityRoutine|null>(STORAGE_KEYS.MORNING_MOBILITY,null)?.date===getTodayDateString()?parse<MorningMobilityRoutine>(STORAGE_KEYS.MORNING_MOBILITY,null as any):({id:`mobility-ready-${getTodayDateString()}`,date:getTodayDateString(),completed:false,isAiGenerated:true,title:'Morning mobility',durationMinutes:0,rationale:'Start mobility to generate a personalized routine.',exercises:[]} as MorningMobilityRoutine);}, saveMorningMobility(r:MorningMobilityRoutine){save(STORAGE_KEYS.MORNING_MOBILITY,r);},
  getNightlyRoutine(){const r=parse<NightlyStretchingRoutine|null>(STORAGE_KEYS.NIGHTLY_ROUTINE,null);return r?.date===getTodayDateString()?r:({id:`nightly-ready-${getTodayDateString()}`,date:getTodayDateString(),completed:false,isAiGenerated:true,title:'Evening recovery',durationMinutes:0,rationale:'Start recovery to generate a personalized routine.',exercises:[]} as NightlyStretchingRoutine);}, saveNightlyRoutine(r:NightlyStretchingRoutine){save(STORAGE_KEYS.NIGHTLY_ROUTINE,r);},
  getPlyometricsRoutine(){const r=parse<PlyometricsRoutine|null>(STORAGE_KEYS.PLYOMETRICS_ROUTINE,null);return r?.date===getTodayDateString()?r:({id:`plyo-ready-${getTodayDateString()}`,date:getTodayDateString(),completed:false,isAiGenerated:true,title:'Athletic power',durationMinutes:0,rationale:'Start plyometrics to generate a personalized routine.',exercises:[]} as PlyometricsRoutine);}, savePlyometricsRoutine(r:PlyometricsRoutine){save(STORAGE_KEYS.PLYOMETRICS_ROUTINE,r);},
  getCustomWorkoutTemplates(){return parse<WorkoutPlan[]>(STORAGE_KEYS.CUSTOM_TEMPLATES,[]);},saveCustomWorkoutTemplates(t:WorkoutPlan[]){save(STORAGE_KEYS.CUSTOM_TEMPLATES,t);},addCustomWorkoutTemplate(t:WorkoutPlan){const a=this.getCustomWorkoutTemplates();const i=a.findIndex(x=>x.id===t.id);if(i>=0)a[i]=t;else a.unshift(t);this.saveCustomWorkoutTemplates(a);},
  getSchoolWorkoutLogs(){return parse<SchoolWorkoutLog[]>(STORAGE_KEYS.SCHOOL_WORKOUT_LOGS,[]);},saveSchoolWorkoutLogs(l:SchoolWorkoutLog[]){save(STORAGE_KEYS.SCHOOL_WORKOUT_LOGS,l);},addSchoolWorkoutLog(l:SchoolWorkoutLog){const a=this.getSchoolWorkoutLogs();const k=l.weightliftingDate||l.date;const i=a.findIndex(x=>(x.weightliftingDate||x.date)===k&&(x.practiceDate||'')===(l.practiceDate||''));if(i>=0)a[i]=l;else a.unshift(l);this.saveSchoolWorkoutLogs(a);},getTodaySchoolWorkoutLog(){const t=getTodayDateString();return this.getSchoolWorkoutLogs().find(l=>(l.weightliftingDate||l.date)===t||(l.practiceDate||l.date)===t)||null;},getRecentSchoolLogs(n=7){return [...this.getSchoolWorkoutLogs()].sort((a,b)=>(b.weightliftingDate||b.date).localeCompare(a.weightliftingDate||a.date)).slice(0,n);},deleteSchoolWorkoutLog(id:string){this.saveSchoolWorkoutLogs(this.getSchoolWorkoutLogs().filter(l=>l.id!==id));},
  getActivityLog(){return parse<Array<{date:string;type:'mobility'|'nightly'|'plyometrics';amount?:number}>>(STORAGE_KEYS.ACTIVITY_LOG,[]);},recordActivity(type:'mobility'|'nightly'|'plyometrics',date:string,amount=1){const a=this.getActivityLog();const n={date,type,amount};const i=a.findIndex(x=>x.date===date&&x.type===type);if(i>=0)a[i]=n;else a.push(n);save(STORAGE_KEYS.ACTIVITY_LOG,a);},
  getTrainingSnapshot(){return {activityLog:this.getActivityLog(),mobility:this.getMorningMobility(),nightlyRoutine:this.getNightlyRoutine(),plyometricsRoutine:this.getPlyometricsRoutine()};},
  calculateDailyStreak(){const d=new Set<string>();this.getWorkoutHistory().forEach(w=>{if(w.status==='completed'||w.completedAt)d.add(w.date);});this.getSchoolWorkoutLogs().forEach(l=>{if(l.hadWeightliftingClass)d.add(l.weightliftingDate||l.date);if(l.hadPractice)d.add(l.practiceDate||l.date);});this.getActivityLog().forEach(a=>d.add(a.date));const today=getTodayDateString();let c=new Date(`${today}T12:00:00`);if(!d.has(today))c.setDate(c.getDate()-1);let currentStreak=0;while(d.has(c.toISOString().split('T')[0])){currentStreak++;c.setDate(c.getDate()-1);}const sorted=[...d].sort();let bestStreak=0,run=0,prev:Date|null=null;for(const x of sorted){const cur=new Date(`${x}T12:00:00`);const gap=prev?Math.round((cur.getTime()-prev.getTime())/86400000):0;run=gap===1?run+1:1;bestStreak=Math.max(bestStreak,run);prev=cur;}return{currentStreak,bestStreak,activeDaysThisMonth:sorted.filter(x=>x.startsWith(today.slice(0,7))).length,lastActiveDate:sorted.at(-1)||'',isActiveToday:d.has(today)};},
  calculateAccumulatedVolume(){let totalWeightVolume=0,totalWorkoutsCompleted=0,totalMinutesTrained=0,totalSetsCompleted=0,thisWeekVolume=0;const cutoff=Date.now()-7*86400000;this.getWorkoutHistory().forEach(w=>{if(w.status!=='completed'&&!w.completedAt)return;totalWorkoutsCompleted++;totalMinutesTrained+=w.actualMinutes||w.estimatedMinutes||0;(w.exercises||[]).forEach(ex=>{const sets=(ex.completedSets||[]).filter(s=>s.completed);if(sets.length)sets.forEach(s=>{totalSetsCompleted++;const v=(s.weight||0)*(s.reps||0);totalWeightVolume+=v;if(new Date(`${w.date}T12:00:00`).getTime()>=cutoff)thisWeekVolume+=v;});});});const activity=this.getActivityLog();return{totalWeightVolume,totalWorkoutsCompleted,totalMinutesTrained,totalPlyometricJumps:activity.filter(a=>a.type==='plyometrics').reduce((s,a)=>s+(a.amount||0),0),totalMobilityCompleted:activity.filter(a=>a.type==='mobility'||a.type==='nightly').length,thisWeekVolume,totalSetsCompleted};},
  getChatMessages(){return parse<ChatMessage[]>(STORAGE_KEYS.CHAT_MESSAGES,[]);},saveChatMessages(m:ChatMessage[]){save(STORAGE_KEYS.CHAT_MESSAGES,m);},getUserAccount(){return parse(STORAGE_KEYS.USER_ACCOUNT,null);},saveUserAccount(a:any|null){if(a)save(STORAGE_KEYS.USER_ACCOUNT,a);else{try{localStorage.removeItem(STORAGE_KEYS.USER_ACCOUNT);}catch{}}},
  async syncAllToCloud(account:any,payload:any){if(!account?.identifier)return false;try{const res=await apiFetch('/api/cloud-sync/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier:account.identifier,data:payload})});return res.ok;}catch{return false;}},
  async loadAllFromCloud(identifier:string){try{const res=await apiFetch(`/api/cloud-sync/load/${encodeURIComponent(identifier)}`);if(!res.ok)return null;const j=await res.json();return j?.data||null;}catch{return null;}},
  resetAll(){localStorage.clear();},clearAll(){localStorage.clear();}
};
export const storageService=StorageService;
